/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: DmxP+iMuLLF7mix7E8nRlG5L1LwARxvq7CHdCacNx7yQ/czWDEEwdtndpbbrOSPazYfmspiEqI/PfnLsbAZ7Ng==
 */

/* eslint-disable */
// tslint:disable

interface DefichainBlocks {
  created_at: (Date) | null
  difficulty: (number) | null
  hash: (string) | null
  height: number & {readonly __brand?: 'defichain_blocks_height'}
  masternode: (string) | null
  minter: (string) | null
  minter_block_count: (number) | null
  reward: (number) | null
  transaction_count: (number) | null
}
export default DefichainBlocks;

interface DefichainBlocks_InsertParameters {
  created_at?: (Date) | null
  difficulty?: (number) | null
  hash?: (string) | null
  height: number & {readonly __brand?: 'defichain_blocks_height'}
  masternode?: (string) | null
  minter?: (string) | null
  minter_block_count?: (number) | null
  reward?: (number) | null
  transaction_count?: (number) | null
}
export type {DefichainBlocks_InsertParameters}
