/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: CCsB1rpJiyGfApKmvdg7Tv/k47cyhCuMpXpGPmtDzrAHlnX85Ap2PYZglgrA2etSJVoL98+mnhrSIMP+Bce/8g==
 */

/* eslint-disable */
// tslint:disable

import DefichainBlocks from './defichain_blocks'
import DefichainTokens from './defichain_tokens'

interface DefichainRewards {
  block_height: (DefichainBlocks['height']) | null
  id: number
  owner: (string) | null
  poolid: (DefichainTokens['tokenid']) | null
  rewardtype: (string) | null
  tokenamount: (number) | null
  tokenid: (DefichainTokens['tokenid']) | null
}
export default DefichainRewards;

interface DefichainRewards_InsertParameters {
  block_height?: (DefichainBlocks['height']) | null
  id?: number
  owner?: (string) | null
  poolid?: (DefichainTokens['tokenid']) | null
  rewardtype?: (string) | null
  tokenamount?: (number) | null
  tokenid?: (DefichainTokens['tokenid']) | null
}
export type {DefichainRewards_InsertParameters}
