/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: SkEzePzcwfy/3dkCTd3lQ6f9j1y2XqniusXUzAs7SYbmhaVFFrco2po80Tp6fd6DMrvBssow3XucNNpl61uNLw==
 */

/* eslint-disable */
// tslint:disable

import DefichainAccountTransactions from './defichain_account_transactions'
import DefichainTokens from './defichain_tokens'

interface DefichainAccountTransactionsAmounts {
  id: number
  token_amount: (number) | null
  tokenid: (DefichainTokens['tokenid']) | null
  transaction_id: (DefichainAccountTransactions['id']) | null
}
export default DefichainAccountTransactionsAmounts;

interface DefichainAccountTransactionsAmounts_InsertParameters {
  id?: number
  token_amount?: (number) | null
  tokenid?: (DefichainTokens['tokenid']) | null
  transaction_id?: (DefichainAccountTransactions['id']) | null
}
export type {DefichainAccountTransactionsAmounts_InsertParameters}
