/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: kkvz4avoln9p0++lt5qpR3u/v405TLQAF4+Klq64mnOP/qqJRIUs1jN0nu0VIklZnp4HHh0UzbiNuP9l0ayGtA==
 */

/* eslint-disable */
// tslint:disable

import DefichainBlocks from './defichain_blocks'
import DefichainTransactions from './defichain_transactions'

interface DefichainAccountTransactions {
  block_height: (DefichainBlocks['height']) | null
  id: number
  owner: (string) | null
  transaction_id: (DefichainTransactions['transaction_id']) | null
  txn: (number) | null
  type: (string) | null
}
export default DefichainAccountTransactions;

interface DefichainAccountTransactions_InsertParameters {
  block_height?: (DefichainBlocks['height']) | null
  id?: number
  owner?: (string) | null
  transaction_id?: (DefichainTransactions['transaction_id']) | null
  txn?: (number) | null
  type?: (string) | null
}
export type {DefichainAccountTransactions_InsertParameters}
