/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: gdVNQbKvTWEBQX3iNciRn5nHni5nv3EaF3RFawqHKhbC4lictO/Xs4CZk5KbqrRl+m/e1QhmMHNc+yzUeL8tDw==
 */

/* eslint-disable */
// tslint:disable

import DefichainBlocks from './defichain_blocks'

interface DefichainTransactions {
  block_height: (DefichainBlocks['height']) | null
  total_vout_value: (number) | null
  transaction_id: string & {readonly __brand?: 'defichain_transactions_transaction_id'}
  tx_order: (number) | null
  vin_count: (number) | null
  vout_count: (number) | null
}
export default DefichainTransactions;

interface DefichainTransactions_InsertParameters {
  block_height?: (DefichainBlocks['height']) | null
  total_vout_value?: (number) | null
  transaction_id: string & {readonly __brand?: 'defichain_transactions_transaction_id'}
  tx_order?: (number) | null
  vin_count?: (number) | null
  vout_count?: (number) | null
}
export type {DefichainTransactions_InsertParameters}
