/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: vx/F/KHyTUwFFod/k+sZqLl16JCoDwOkkfH1ZYlvyIOLbFsRU5Z5qfhkMpWQCuNf2aKzbpivkIXJbldJB5EN0Q==
 */

/* eslint-disable */
// tslint:disable

import DefichainTokens from './defichain_tokens'
import DefichainTransactions from './defichain_transactions'

interface DefichainVinsVouts {
  owner: (string) | null
  token_amount: (number) | null
  tokenid: (DefichainTokens['tokenid']) | null
  transaction_id: (DefichainTransactions['transaction_id']) | null
}
export default DefichainVinsVouts;

interface DefichainVinsVouts_InsertParameters {
  owner?: (string) | null
  token_amount?: (number) | null
  tokenid?: (DefichainTokens['tokenid']) | null
  transaction_id?: (DefichainTransactions['transaction_id']) | null
}
export type {DefichainVinsVouts_InsertParameters}
