/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: uPzPavrSjAsf6x0zhRUBxW7nuGX50PksKG0LuQsSoGTfr+Zb1OZXn1JN/bLeWOdbMGvgR2YnqKaoSTL5y/jPBw==
 */

/* eslint-disable */
// tslint:disable

import DefichainAccountTransactions, {DefichainAccountTransactions_InsertParameters} from './defichain_account_transactions'
import DefichainAccountTransactionsAmounts, {DefichainAccountTransactionsAmounts_InsertParameters} from './defichain_account_transactions_amounts'
import DefichainBlocks, {DefichainBlocks_InsertParameters} from './defichain_blocks'
import DefichainRewards, {DefichainRewards_InsertParameters} from './defichain_rewards'
import DefichainTokens, {DefichainTokens_InsertParameters} from './defichain_tokens'
import DefichainTransactions, {DefichainTransactions_InsertParameters} from './defichain_transactions'
import DefichainVinsVouts, {DefichainVinsVouts_InsertParameters} from './defichain_vins_vouts'

interface DatabaseSchema {
  defichain_account_transactions: {record: DefichainAccountTransactions, insert: DefichainAccountTransactions_InsertParameters};
  defichain_account_transactions_amounts: {record: DefichainAccountTransactionsAmounts, insert: DefichainAccountTransactionsAmounts_InsertParameters};
  defichain_blocks: {record: DefichainBlocks, insert: DefichainBlocks_InsertParameters};
  defichain_rewards: {record: DefichainRewards, insert: DefichainRewards_InsertParameters};
  defichain_tokens: {record: DefichainTokens, insert: DefichainTokens_InsertParameters};
  defichain_transactions: {record: DefichainTransactions, insert: DefichainTransactions_InsertParameters};
  defichain_vins_vouts: {record: DefichainVinsVouts, insert: DefichainVinsVouts_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  DefichainBlocks,
  DefichainBlocks_InsertParameters,
  DefichainTransactions,
  DefichainTransactions_InsertParameters,
  DefichainAccountTransactions,
  DefichainAccountTransactions_InsertParameters,
  DefichainTokens,
  DefichainTokens_InsertParameters,
  DefichainAccountTransactionsAmounts,
  DefichainAccountTransactionsAmounts_InsertParameters,
  DefichainRewards,
  DefichainRewards_InsertParameters,
  DefichainVinsVouts,
  DefichainVinsVouts_InsertParameters,
}
